### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by rm-vienna** [CodeYellowBV/django-relativedelta#1]
Hi,

I get the following error when using the django-relativedelta:

raise ValueError(_('RelativeDeltaField only supports PostgreSQL for storage'))
ValueError: RelativeDeltaField only supports PostgreSQL for storage

Since postgresql and postgresql_psycopg2 are the same, I believe line 94 in relativedeltafield/init.py should be:

if connection.settings_dict['ENGINE'] in ('django.db.backends.postgresql_psycopg2', 'django.db.backends.postgresql'):

Thank you!

**Comment by sjamaan** [comment]
Can you test the current master?

**Comment by rm-vienna** [comment]
Looks good! Thx

**Comment by sjamaan** [comment]
Thanks for reporting and testing!
