### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by narrowfail** [CodeYellowBV/django-relativedelta#23]
Hello, right now I had to copy your code in my repo since it doesn't support Django 4.0. Would be nice to support it.

Thanks!

**Comment by stefanmajoor** [comment]
Hi Narrowfall,

This is on our todo list!

**Comment by sevdog** [comment]
This month it was also released  [Django 4.1](https://docs.djangoproject.com/en/4.1/releases/4.1/), is there an ETA for these versions to be supported/tested?

**Comment by sevdog** [comment]
There are two PR (#25 and #26) which should address this issue, is any of those going to be merged and released in the near future?

**Comment by sevdog** [comment]
Now there is also the [4.2-alpha](https://www.djangoproject.com/weblog/2023/jan/17/django-42-alpha-1-released/) release, is this package going to be updated to support this?

**Comment by sjamaan** [comment]
> Now there is also the [4.2-alpha](https://www.djangoproject.com/weblog/2023/jan/17/django-42-alpha-1-released/) release, is this package going to be updated to support this?

At this point I'd suggest just forking the package - there seems to be no interest at Code Yellow to take up the maintenance of this package. I'm rather disappointed that my project has turned out to be neglected like this :disappointed:

**Comment by robinzelders** [comment]
Thanks for the interest in the package. I want to inform you that Code Yellow has not fully neglected this package. I will be testing the package in the following days and make sure there is an update. 

Stay tuned...

**Comment by bast-ii** [comment]
Is an update planned to support django 4.0.4?

**Comment by Lekensteyn** [comment]
It appears that #26 got merged, so all that is needed is a new release.

**Comment by sergei-maertens** [comment]
@robinzelders with the Django 4.2 release - how are things looking? Is there anything blocking a new PyPI release?

**Comment by BBooijLiewes** [comment]
hey @sergei-maertens [version 2.0.0](https://pypi.org/project/django-relativedelta/2.0.0/) has just been released to PyPI, let us know if you need anything else or discover any bugs :+1:.

Support for Django 4.2 would require a bit more work I believe so lets open a separate issue for that if needed.
