### ISSUE TITLE
Support for Django 3.0

### ISSUE THREAD

**Issue by emanuelmd** [CodeYellowBV/django-relativedelta#9]
Hello, in our company Secfi, we're using this library along with Django.
Recently we looked at migrating our project to Django 3.0 and this package is the only one that prevents us to do so.

My question is, are you planning to add Django 3.0 support for it?
We can also take a stab and submit a PR but I'll have to consult with my colleagues.

**Comment by sjamaan** [comment]
Hi there! We're certainly going to migrate our projects to Django 3 at some point, but the two projects in which I'm using this are relatively complex, so I don't know when we will get around to this.

If you can make a PR which adds Django 3 support before that time, I'd be happy to review it of course.

From what I've gathered, the internal API has changed a little bit, so providing support for both 3.0 and 2.x at the same time (which I'd go for) is going to be the challenge.

**Comment by sjamaan** [comment]
Should now be released on Pypi as django-relativedelta 1.1.0. Thanks again!

**Comment by emanuelmd** [comment]
Thank you for your quick response and help. Fix by #10
